include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # Signature files - intentionally incomplete API documentation
    # All signature files end with _signature.dart
    - lib/get_it/*_signature.dart
    # Exclude package dependencies from analysis (path dependencies in parent directory)
    - "../../get_it/**"
    - "../../watch_it/**"
    - "../../command_it/**"
    - "../../listen_it/**"

  errors:
    # Be strict about actual errors
    undefined_identifier: error
    undefined_class: error
    invalid_assignment: error
    # Suppress info messages that don't matter for example code
    unused_local_variable: ignore
    unnecessary_import: ignore
    deprecated_member_use: ignore

linter:
  rules:
    # Disable rules that don't make sense for example code
    public_member_api_docs: false
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    avoid_print: false
    use_key_in_widget_constructors: false
    unnecessary_string_interpolations: false
    annotate_overrides: false
    use_build_context_synchronously: false
    prefer_final_fields: false
    # Enable important rules
    avoid_relative_lib_imports: true
    unnecessary_null_checks: true
