include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # Signature files - intentionally incomplete API documentation
    - lib/get_it/*_signature.dart
    # Additional signature files (missing_function_body ignore comment)
    - lib/get_it/code_sample_12625bd9.dart
    - lib/get_it/code_sample_30935190.dart
    - lib/get_it/code_sample_32653109.dart
    - lib/get_it/code_sample_3c73f756.dart
    - lib/get_it/code_sample_3ddc0f1f.dart
    - lib/get_it/code_sample_773e24bb.dart
    - lib/get_it/code_sample_f4194899.dart
    - lib/get_it/code_sample_fdab4a35.dart
    # Function signature examples (no function body)
    - lib/get_it/t_example.dart
    - lib/get_it/t_example_1.dart
    - lib/get_it/function_example.dart
    - lib/get_it/function_example_1.dart
    - lib/get_it/function_example_2.dart
    - lib/get_it/reset_example.dart
    - lib/get_it/release_instance_example.dart
    - lib/get_it/reset_lazy_singletons_example.dart

  errors:
    # Be strict about actual errors
    undefined_identifier: error
    undefined_class: error
    invalid_assignment: error

linter:
  rules:
    # Disable rules that don't make sense for example code
    public_member_api_docs: false
    prefer_const_constructors: false
    avoid_print: false
    # Enable important rules
    avoid_relative_lib_imports: true
    prefer_final_fields: true
    unnecessary_null_checks: true
